version: '3.8'

services:
  rrc-drl:
    build:
      context: .
      dockerfile: Dockerfile
    image: rrc-drl-image
    container_name: rrc-drl-container
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - PATH_SIMULATION=/app
      - PYTHONUNBUFFERED=1
    tty: true
    stdin_open: true
    command: python ./run_all_combinations.py